export const countryData = [
    { id: 1, Country: "Afghanistan", "country_code": "AF" },
    { id: 2, Country: "land Islands", "country_code": "AX" },
    { id: 3, Country: "Albania", "country_code": "AL" },
    { id: 4, Country: "Algeria", "country_code": "DZ" },
    { id: 5, Country: "American Samoa", "country_code": "AS" },
    { id: 6, Country: "AndorrA", "country_code": "AD" },
    { id: 7, Country: "Angola", "country_code": "AO" },
    { id: 8, Country: "Anguilla", "country_code": "AI" },
    { id: 9, Country: "Antarctica", "country_code": "AQ" },
    { id: 10, Country: "Antigua and Barbuda", "country_code": "AG" },
    { id: 11, Country: "Argentina", "country_code": "AR" },
    { id: 12, Country: "Armenia", "country_code": "AM" },
    { id: 13, Country: "Aruba", "country_code": "AW" },
    { id: 14, Country: "Australia", "country_code": "AU" },
    { id: 15, Country: "Austria", "country_code": "AT" },
    { id: 16, Country: "Azerbaijan", "country_code": "AZ" },
    { id: 17, Country: "Bahamas", "country_code": "BS" },
    { id: 18, Country: "Bahrain", "country_code": "BH" },
    { id: 19, Country: "Bangladesh", "country_code": "BD" },
    { id: 20, Country: "Barbados", "country_code": "BB" },
    { id: 21, Country: "Belarus", "country_code": "BY" },
    { id: 22, Country: "Belgium", "country_code": "BE" },
    { id: 23, Country: "Belize", "country_code": "BZ" },
    { id: 24, Country: "Benin", "country_code": "BJ" },
    { id: 25, Country: "Bermuda", "country_code": "BM" },
    { id: 26, Country: "Bhutan", "country_code": "BT" },
    { id: 27, Country: "Bolivia", "country_code": "BO" },
    { id: 28, Country: "Bosnia and Herzegovina", "country_code": "BA" },
    { id: 29, Country: "Botswana", "country_code": "BW" },
    { id: 30, Country: "Bouvet Island", "country_code": "BV" },
    { id: 31, Country: "Brazil", "country_code": "BR" },
    { id: 32, Country: "British Indian Ocean Territory", "country_code": "IO" },
    { id: 33, Country: "Brunei Darussalam", "country_code": "BN" },
    { id: 34, Country: "Bulgaria", "country_code": "BG" },
    { id: 35, Country: "Burkina Faso", "country_code": "BF" },
    { id: 36, Country: "Burundi", "country_code": "BI" },
    { id: 37, Country: "Cambodia", "country_code": "KH" },
    { id: 38, Country: "Cameroon", "country_code": "CM" },
    { id: 39, Country: "Canada", "country_code": "CA" },
    { id: 40, Country: "Cape Verde", "country_code": "CV" },
    { id: 41, Country: "Cayman Islands", "country_code": "KY" },
    { id: 42, Country: "Central African Republic", "country_code": "CF" },
    { id: 43, Country: "Chad", "country_code": "TD" },
    { id: 44, Country: "Chile", "country_code": "CL" },
    { id: 45, Country: "China", "country_code": "CN" },
    { id: 46, Country: "Christmas Island", "country_code": "CX" },
    { id: 47, Country: "Cocos (Keeling) Islands", "country_code": "CC" },
    { id: 48, Country: "Colombia", "country_code": "CO" },
    { id: 49, Country: "Comoros", "country_code": "KM" },
    { id: 50, Country: "Congo", "country_code": "CG" },
    { id: 51, Country: "Congo, The Democratic Republic of the", "country_code": "CD" },
    { id: 52, Country: "Cook Islands", "country_code": "CK" },
    { id: 53, Country: "Costa Rica", "country_code": "CR" },
    { id: 54, Country: "Cote D\"Ivoire", "country_code": "CI" },
    { id: 55, Country: "Croatia", "country_code": "HR" },
    { id: 56, Country: "Cuba", "country_code": "CU" },
    { id: 57, Country: "Cyprus", "country_code": "CY" },
    { id: 58, Country: "Czech Republic", "country_code": "CZ" },
    { id: 59, Country: "Denmark", "country_code": "DK" },
    { id: 60, Country: "Djibouti", "country_code": "DJ" },
    { id: 61, Country: "Dominica", "country_code": "DM" },
    { id: 62, Country: "Dominican Republic", "country_code": "DO" },
    { id: 63, Country: "Ecuador", "country_code": "EC" },
    { id: 64, Country: "Egypt", "country_code": "EG" },
    { id: 65, Country: "El Salvador", "country_code": "SV" },
    { id: 66, Country: "Equatorial Guinea", "country_code": "GQ" },
    { id: 67, Country: "Eritrea", "country_code": "ER" },
    { id: 68, Country: "Estonia", "country_code": "EE" },
    { id: 69, Country: "Ethiopia", "country_code": "ET" },
    { id: 70, Country: "Falkland Islands (Malvinas)", "country_code": "FK" },
    { id: 71, Country: "Faroe Islands", "country_code": "FO" },
    { id: 72, Country: "Fiji", "country_code": "FJ" },
    { id: 73, Country: "Finland", "country_code": "FI" },
    { id: 74, Country: "France", "country_code": "FR" },
    { id: 75, Country: "French Guiana", "country_code": "GF" },
    { id: 76, Country: "French Polynesia", "country_code": "PF" },
    { id: 77, Country: "French Southern Territories", "country_code": "TF" },
    { id: 78, Country: "Gabon", "country_code": "GA" },
    { id: 79, Country: "Gambia", "country_code": "GM" },
    { id: 80, Country: "Georgia", "country_code": "GE" },
    { id: 81, Country: "Germany", "country_code": "DE" },
    { id: 82, Country: "Ghana", "country_code": "GH" },
    { id: 83, Country: "Gibraltar", "country_code": "GI" },
    { id: 84, Country: "Greece", "country_code": "GR" },
    { id: 85, Country: "Greenland", "country_code": "GL" },
    { id: 86, Country: "Grenada", "country_code": "GD" },
    { id: 87, Country: "Guadeloupe", "country_code": "GP" },
    { id: 88, Country: "Guam", "country_code": "GU" },
    { id: 89, Country: "Guatemala", "country_code": "GT" },
    { id: 90, Country: "Guernsey", "country_code": "GG" },
    { id: 91, Country: "Guinea", "country_code": "GN" },
    { id: 92, Country: "Guinea-Bissau", "country_code": "GW" },
    { id: 93, Country: "Guyana", "country_code": "GY" },
    { id: 94, Country: "Haiti", "country_code": "HT" },
    { id: 95, Country: "Heard Island and Mcdonald Islands", "country_code": "HM" },
    { id: 96, Country: "Holy See (Vatican City State)", "country_code": "VA" },
    { id: 97, Country: "Honduras", "country_code": "HN" },
    { id: 98, Country: "Hong Kong", "country_code": "HK" },
    { id: 99, Country: "Hungary", "country_code": "HU" },
    { id: 100, Country: "Iceland", "country_code": "IS" },
    { id: 101, Country: "India", "country_code": "IN" },
    { id: 102, Country: "Indonesia", "country_code": "ID" },
    { id: 103, Country: "Iran, Islamic Republic Of", "country_code": "IR" },
    { id: 104, Country: "Iraq", "country_code": "IQ" },
    { id: 105, Country: "Ireland", "country_code": "IE" },
    { id: 106, Country: "Isle of Man", "country_code": "IM" },
    { id: 107, Country: "Israel", "country_code": "IL" },
    { id: 108, Country: "Italy", "country_code": "IT" },
    { id: 109, Country: "Jamaica", "country_code": "JM" },
    { id: 110, Country: "Japan", "country_code": "JP" },
    { id: 111, Country: "Jersey", "country_code": "JE" },
    { id: 112, Country: "Jordan", "country_code": "JO" },
    { id: 113, Country: "Kazakhstan", "country_code": "KZ" },
    { id: 114, Country: "Kenya", "country_code": "KE" },
    { id: 115, Country: "Kiribati", "country_code": "KI" },
    { id: 116, Country: "Korea, Democratic People\"S Republic of", "country_code": "KP" },
    { id: 117, Country: "Korea, Republic of", "country_code": "KR" },
    { id: 118, Country: "Kuwait", "country_code": "KW" },
    { id: 119, Country: "Kyrgyzstan", "country_code": "KG" },
    { id: 120, Country: "Lao People\"S Democratic Republic", "country_code": "LA" },
    { id: 121, Country: "Latvia", "country_code": "LV" },
    { id: 122, Country: "Lebanon", "country_code": "LB" },
    { id: 123, Country: "Lesotho", "country_code": "LS" },
    { id: 124, Country: "Liberia", "country_code": "LR" },
    { id: 125, Country: "Libyan Arab Jamahiriya", "country_code": "LY" },
    { id: 126, Country: "Liechtenstein", "country_code": "LI" },
    { id: 127, Country: "Lithuania", "country_code": "LT" },
    { id: 128, Country: "Luxembourg", "country_code": "LU" },
    { id: 129, Country: "Macao", "country_code": "MO" },
    { id: 130, Country: "Macedonia, The Former Yugoslav Republic of", "country_code": "MK" },
    { id: 131, Country: "Madagascar", "country_code": "MG" },
    { id: 132, Country: "Malawi", "country_code": "MW" },
    { id: 133, Country: "Malaysia", "country_code": "MY" },
    { id: 134, Country: "Maldives", "country_code": "MV" },
    { id: 135, Country: "Mali", "country_code": "ML" },
    { id: 136, Country: "Malta", "country_code": "MT" },
    { id: 137, Country: "Marshall Islands", "country_code": "MH" },
    { id: 138, Country: "Martinique", "country_code": "MQ" },
    { id: 140, Country: "Mauritania", "country_code": "MR" },
    { id: 141, Country: "Mauritius", "country_code": "MU" },
    { id: 142, Country: "Mayotte", "country_code": "YT" },
    { id: 143, Country: "Mexico", "country_code": "MX" },
    { id: 144, Country: "Micronesia, Federated States of", "country_code": "FM" },
    { id: 145, Country: "Moldova, Republic of", "country_code": "MD" },
    { id: 146, Country: "Monaco", "country_code": "MC" },
    { id: 147, Country: "Mongolia", "country_code": "MN" },
    { id: 148, Country: "Montenegro", "country_code": "ME" },
    { id: 149, Country: "Montserrat", "country_code": "MS" },
    { id: 150, Country: "Morocco", "country_code": "MA" },
    { id: 151, Country: "Mozambique", "country_code": "MZ" },
    { id: 152, Country: "Myanmar", "country_code": "MM" },
    { id: 153, Country: "Namibia", "country_code": "NA" },
    { id: 154, Country: "Nauru", "country_code": "NR" },
    { id: 155, Country: "Nepal", "country_code": "NP" },
    { id: 156, Country: "Netherlands", "country_code": "NL" },
    { id: 157, Country: "Netherlands Antilles", "country_code": "AN" },
    { id: 158, Country: "New Caledonia", "country_code": "NC" },
    { id: 159, Country: "New Zealand", "country_code": "NZ" },
    { id: 160, Country: "Nicaragua", "country_code": "NI" },
    { id: 161, Country: "Niger", "country_code": "NE" },
    { id: 162, Country: "Nigeria", "country_code": "NG" },
    { id: 163, Country: "Niue", "country_code": "NU" },
    { id: 164, Country: "Norfolk Island", "country_code": "NF" },
    { id: 165, Country: "Northern Mariana Islands", "country_code": "MP" },
    { id: 166, Country: "Norway", "country_code": "NO" },
    { id: 167, Country: "Oman", "country_code": "OM" },
    { id: 168, Country: "Pakistan", "country_code": "PK" },
    { id: 169, Country: "Palau", "country_code": "PW" },
    { id: 170, Country: "Palestinian Territory, Occupied", "country_code": "PS" },
    { id: 171, Country: "Panama", "country_code": "PA" },
    { id: 172, Country: "Papua New Guinea", "country_code": "PG" },
    { id: 173, Country: "Paraguay", "country_code": "PY" },
    { id: 174, Country: "Peru", "country_code": "PE" },
    { id: 175, Country: "Philippines", "country_code": "PH" },
    { id: 176, Country: "Pitcairn", "country_code": "PN" },
    { id: 177, Country: "Poland", "country_code": "PL" },
    { id: 178, Country: "Portugal", "country_code": "PT" },
    { id: 179, Country: "Puerto Rico", "country_code": "PR" },
    { id: 180, Country: "Qatar", "country_code": "QA" },
    { id: 181, Country: "Reunion", "country_code": "RE" },
    { id: 182, Country: "Romania", "country_code": "RO" },
    { id: 183, Country: "Russian Federation", "country_code": "RU" },
    { id: 184, Country: "RWANDA", "country_code": "RW" },
    { id: 185, Country: "Saint Helena", "country_code": "SH" },
    { id: 186, Country: "Saint Kitts and Nevis", "country_code": "KN" },
    { id: 187, Country: "Saint Lucia", "country_code": "LC" },
    { id: 188, Country: "Saint Pierre and Miquelon", "country_code": "PM" },
    { id: 189, Country: "Saint Vincent and the Grenadines", "country_code": "VC" },
    { id: 190, Country: "Samoa", "country_code": "WS" },
    { id: 191, Country: "San Marino", "country_code": "SM" },
    { id: 192, Country: "Sao Tome and Principe", "country_code": "ST" },
    { id: 193, Country: "Saudi Arabia", "country_code": "SA" },
    { id: 194, Country: "Senegal", "country_code": "SN" },
    { id: 195, Country: "Serbia", "country_code": "RS" },
    { id: 196, Country: "Seychelles", "country_code": "SC" },
    { id: 197, Country: "Sierra Leone", "country_code": "SL" },
    { id: 198, Country: "Singapore", "country_code": "SG" },
    { id: 199, Country: "Slovakia", "country_code": "SK" },
    { id: 200, Country: "Slovenia", "country_code": "SI" },
    { id: 201, Country: "Solomon Islands", "country_code": "SB" },
    { id: 202, Country: "Somalia", "country_code": "SO" },
    { id: 203, Country: "South Africa", "country_code": "ZA" },
    { id: 204, Country: "South Georgia and the South Sandwich Islands", "country_code": "GS" },
    { id: 205, Country: "Spain", "country_code": "ES" },
    { id: 206, Country: "Sri Lanka", "country_code": "LK" },
    { id: 207, Country: "Sudan", "country_code": "SD" },
    { id: 208, Country: "Suriname", "country_code": "SR" },
    { id: 209, Country: "Svalbard and Jan Mayen", "country_code": "SJ" },
    { id: 210, Country: "Swaziland", "country_code": "SZ" },
    { id: 211, Country: "Sweden", "country_code": "SE" },
    { id: 212, Country: "Switzerland", "country_code": "CH" },
    { id: 213, Country: "Syrian Arab Republic", "country_code": "SY" },
    { id: 214, Country: "Taiwan, Province of China", "country_code": "TW" },
    { id: 215, Country: "Tajikistan", "country_code": "TJ" },
    { id: 216, Country: "Tanzania, United Republic of", "country_code": "TZ" },
    { id: 217, Country: "Thailand", "country_code": "TH" },
    { id: 218, Country: "Timor-Leste", "country_code": "TL" },
    { id: 219, Country: "Togo", "country_code": "TG" },
    { id: 220, Country: "Tokelau", "country_code": "TK" },
    { id: 221, Country: "Tonga", "country_code": "TO" },
    { id: 222, Country: "Trinidad and Tobago", "country_code": "TT" },
    { id: 223, Country: "Tunisia", "country_code": "TN" },
    { id: 224, Country: "Turkey", "country_code": "TR" },
    { id: 225, Country: "Turkmenistan", "country_code": "TM" },
    { id: 226, Country: "Turks and Caicos Islands", "country_code": "TC" },
    { id: 227, Country: "Tuvalu", "country_code": "TV" },
    { id: 228, Country: "Uganda", "country_code": "UG" },
    { id: 229, Country: "Ukraine", "country_code": "UA" },
    { id: 230, Country: "United Arab Emirates", "country_code": "AE" },
    { id: 231, Country: "United Kingdom", "country_code": "GB" },
    { id: 232, Country: "United States", "country_code": "US" },
    { id: 233, Country: "United States Minor Outlying Islands", "country_code": "UM" },
    { id: 234, Country: "Uruguay", "country_code": "UY" },
    { id: 235, Country: "Uzbekistan", "country_code": "UZ" },
    { id: 236, Country: "Vanuatu", "country_code": "VU" },
    { id: 237, Country: "Venezuela", "country_code": "VE" },
    { id: 238, Country: "Viet Nam", "country_code": "VN" },
    { id: 239, Country: "Virgin Islands, British", "country_code": "VG" },
    { id: 240, Country: "Virgin Islands, U.S.", "country_code": "VI" },
    { id: 241, Country: "Wallis and Futuna", "country_code": "WF" },
    { id: 242, Country: "Western Sahara", "country_code": "EH" },
    { id: 243, Country: "Yemen", "country_code": "YE" },
    { id: 244, Country: "Zambia", "country_code": "ZM" },
    { id: 245, Country: "Zimbabwe", "country_code": "ZW" }
]